# Generated by Django 3.2.4 on 2021-06-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210616_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('size', models.CharField(choices=[('S', 'SMALL'), ('L', 'LARGE'), ('XL', 'XL'), ('XXL', 'XXL'), ('M', 'M'), ('FREE', 'FREE'), ('XS', 'XS'), ('XXS', 'XXS'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('38', '38'), ('41', '41'), ('42', '42'), ('43', '43')], max_length=5)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.tshirt')),
            ],
        ),
    ]
