# Generated by Django 3.2.4 on 2021-06-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sizevariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='title',
        ),
    ]
