# Generated by Django 3.2.4 on 2021-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210616_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='discount',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
