# Generated by Django 3.2.4 on 2021-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PLACED', 'Placed'), ('CANCLED', 'Canceled'), ('COMPLETED', 'COMPLETED')], max_length=15),
        ),
    ]
